name: woxsen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  animated_bottom_navigation_bar: ^1.0.0
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  stylish_bottom_bar: ^1.1.0
  url_launcher: 6.3.0
  flutter_launcher_icons: ^0.9.2
  webview_flutter: ^3.0.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  file_picker: ^8.0.6
  path_provider: ^2.1.3
  flutter_pdfview: ^1.3.2
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  syncfusion_flutter_pdfviewer: ^26.1.42


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/top.png
    - assets/download.png
    - assets/bg.png
    - assets/icon/
    - assets/newsletter.pdf
    - assets/oval_timings.pdf
    - assets/oval_data.pdf
    - assets/App_Development.pdf
    - assets/Student_Engagement.pdf
    - shorebird.yaml
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
